// src/renderer/pages/installed/index.vue
<template>
  <div>
    <div v-if="games.length" id="games-list" class="row row-cols-6 p-5">
      <div v-for="game in games" :key="game.identifier" class="col mb-4">
        <gameCard :game="game" />
      </div><!-- /.col -->
    </div><!-- /.row -->
    <div v-else class="row p-5">
      <div class="col">
        <p>
          No games found in the install directory ({{ settings.installDirPathBase.value }}).
        </p>
        <p>
          You can change the install directory location in the <nuxt-link to="/settings">settings</nuxt-link>.
        </p>
      </div>
      <!-- /.col -->
    </div><!-- /.row p-5 -->
  </div>
</template>

<script>
// import { remote } from 'electron'
// import SystemInformation from '@/components/SystemInformation.vue'
import { mapMutations } from 'vuex'
const fs = require('fs')

export default {
  data () {
    return {
      rows: 20,
      totalPages: 0,
      games: [],
      gamesInstalled: []
    }
  },
  fetch () {
    console.log('fetch called')
    this.fetchInstalledGames()
  },
  computed: {
    settings () {
      return this.$store.state.settings
    }
  },
  watch: {
    // page () {
    //   this.fetchGames()
    // }
  },
  mounted () {
    // console.log('index mounted')
    const vm = this
    this.gamesInstalled.forEach(identifier => {
      if (this.$store.state.games.games[identifier]) {
        this.games.push(this.$store.state.games.games[identifier])
      } else {
        console.log(identifier + ' not found in vuex')
        vm.fetchGameDetails(identifier)
          .then(() => {
            vm.games.push(this.$store.state.games.games[identifier])
          })
      }
    })
  },
  methods: {
    ...mapMutations({
      addGame: 'games/add'
    }),
    fetchInstalledGames () {
      fs.readdirSync(this.settings.installDirPathBase.value).forEach(file => {
        this.gamesInstalled.push(file)
      })
    },
    fetchGameDetails (identifier) {
      // eslint-disable-next-line no-new
      return new Promise((resolve, reject) => {
        // fetches games list
        const q = `collection:(softwarelibrary_msdos_games) AND identifier:(${identifier})`
        this.$axios.$get(`https://archive.org/advancedsearch.php?q=${q}&sort[]=downloads desc&fl[]=avg_rating&fl[]=creator&fl[]=downloads&fl[]=genre&fl[]=identifier&fl[]=item_size&fl[]=language&fl[]=name&fl[]=num_reviews&fl[]=oai_updatedate&fl[]=publicdate&fl[]=title&fl[]=type&fl[]=year&sort[]=&sort[]=&sort[]=&rows=${this.rows}&page=${this.page}&output=json`)
          .then(response => {
            console.log(response.responseHeader)
            response.response.docs.forEach(game => {
            // console.log(game.identifier)
              this.addGame(game)
            })
            resolve()
          })
          .catch(e => reject(e))
      })
    }
    // openURL (url) {
    //   remote.shell.openExternal(url)
    // }
  }
}
</script>

<style>
  .game-card {
    min-width: 10em;
    min-height: 17em;
    /* font-size: 1em; */
    top: 0px;
    transition: top ease 0.15s;
  }
  .game-card.bouncing:hover {
    top: -2px;
  }
  .game-card .card-title {
    font-size: 1em;
    /* margin-bottom: 0em; */
  }
  /* .game-card .card-subtitle {
    font-size: 0.8em
  } */
  /* .game-card .game-info {
    font-size: 0.8em
  } */
  .game-card [class^="material-icons-"] {
    font-size: 1.3em;
    top: 1px;
    position: relative;
  }
  .pagination a {
    cursor: default
  }
</style>

// src/renderer/src/pages/Installed.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import GameCard from '../components/GameCard'
import { useStore } from '../state/store'

const fs = window.require('fs')

const Installed = () => {
  const { state, dispatch } = useStore()
  const [games, setGames] = React.useState([])

  React.useEffect(() => {
    const loadInstalled = async () => {
      const installDir = state.settings.installDirPathBase.value
      if (!fs.existsSync(installDir)) {
        setGames([])
        return
      }

      const identifiers = fs.readdirSync(installDir)
      identifiers.forEach((identifier) => {
        dispatch({
          type: 'USER_MARK_INSTALLED',
          payload: { identifier, source: 'filesystem' }
        })
      })

      const resolved = []
      for (const identifier of identifiers) {
        if (state.catalog.games[identifier]) {
          resolved.push(state.catalog.games[identifier])
        } else {
          try {
            const q = `collection:(softwarelibrary_msdos_games) AND identifier:(${identifier})`
            const response = await fetch(
              `https://archive.org/advancedsearch.php?q=${q}&sort[]=downloads desc&fl[]=avg_rating&fl[]=creator&fl[]=downloads&fl[]=genre&fl[]=identifier&fl[]=item_size&fl[]=language&fl[]=name&fl[]=num_reviews&fl[]=oai_updatedate&fl[]=publicdate&fl[]=title&fl[]=type&fl[]=year&rows=1&page=1&output=json`
            )
            const data = await response.json()
            if (data.response.docs.length) {
              const game = data.response.docs[0]
              dispatch({ type: 'CATALOG_ADD_MANY', payload: [game] })
              resolved.push(game)
            }
          } catch (error) {
            console.error(error)
          }
        }
      }

      setGames(resolved)
    }

    loadInstalled()
  }, [state.settings.installDirPathBase.value, dispatch])

  if (!games.length) {
    return (
      <div className="space-y-2 text-sm text-slate-600">
        <p>No games found in the install directory ({state.settings.installDirPathBase.value}).</p>
        <p>
          You can change the install directory location in the{' '}
          <Link className="text-blue-600" to="/settings">
            settings
          </Link>
          .
        </p>
      </div>
    )
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
      {games.map((game) => (
        <GameCard key={game.identifier} game={game} />
      ))}
    </div>
  )
}

export default Installed
